[general]
# INPUT_FOLDER: Default input folder, can be overridden using "--input_folder" option in the CLI.
INPUT_FOLDER = input
# OUTPUT_FOLDER: Default output folder, can be overridden using "--output_folder" option in the CLI.
OUTPUT_FOLDER = output
MOVIES_FOLDER = Movies
MOVIES_HDR_FOLDER = Movies (HDR)
TV_SHOWS_FOLDER = TV Shows
TV_SHOWS_HDR_FOLDER = TV Shows (HDR)
# ANIME_FOLDER: Requires NORMALIZE_FILENAMES to be either 'full' or 'full-jf'
# as it uses the genre metadata from TVMAZE to categorize files as Anime.
ANIME_FOLDER = Anime
OTHERS_FOLDER =
# KEEP_ORIGINAL: Keeps the original file(s) in specified input folder (default)
# Can be overridden using "--move" in the CLI.
KEEP_ORIGINAL = true
# TEMP_DIR: File path used for storing the temporary
# files when using the native Python version. No quotes.
TEMP_DIR = .tmp
# FILE_TAG: If set to 'default' no existing tags will be removed/changed,
# replace 'default' with '-<your tag here>' to change it (like '-TAG')
FILE_TAG =
# NORMALIZE_FILENAMES: Normalizes filenames based on detected media.
# 'Simple' will extract the show name (and year if present), as well as season and episode.
# 'Full' will check the show name and episode using TVMAZE (api.tvmaze.com), and fill in the blanks.
# Jellyfin compatible titles can also be selected with '*-jf' which skips the " - " between show title and name.
#
# false:     "Tv.Show.S01E01.1080p.BluRay.AVC.REMUX.DTS-HD.MA.5.1.mkv"
# simple:    "Tv Show - S01E01.mkv"
# simple-jf: "Tv Show S01E01.mkv"
# full:      "Tv Show (2010) - S01E01 - The title of the episode.mkv"
# full-jf:   "Tv Show (2010) S01E01 The title of the episode.mkv"
# Options: 'full', 'full-jf', 'simple', 'simple-jf', 'false'
NORMALIZE_FILENAMES = full
# MAKE_SEASON_FOLDERS: Creates season folders for identified TV shows in output folder
# Example: "Tv.Show.Name.S01E01.mkv" -> "TV Show Name/Season 1/Tv.Show.Name.S01E01.mkv"
# Options: 'true', 'false'
MAKE_SEASON_FOLDERS = true
# REMOVE_ALL_TITLE_NAMES: Removes title names from all video, audio and subtitle tracks in the MKV file.
# Options: 'true', 'false'
REMOVE_ALL_TITLE_NAMES = false
# KEEP_ORIGINAL_FILE_STRUCTURE: Keeps the original folder structure of files when moving to output folder.
# 'true' will ignore all media type categorizations and simply copy the folder structure
# 'fallback' will use default media categorization for TV/Movies, but use the original
#            folder structure if the file is uncategorized (Others folder)
# 'false' will simply flatten all original folders and just use the media categorization folders.
KEEP_ORIGINAL_FILE_STRUCTURE = fallback
# REMOVE_SAMPLES: Folders named "Sample" or "sample", as well as files
# ending in '-sample' will be removed if set to 'true'
# Options: 'true', 'false'
REMOVE_SAMPLES = true
# MAX_CPU_USAGE: The max amount (percent) of
# CPU threads to be used for processing.
MAX_CPU_USAGE = 85
# MAX_RAM_USAGE: The max amount (percent) of
# RAM to be used when performing OCR on subtitles.
MAX_RAM_USAGE = 85
# DEBUG: Prints debug info such as command line parameters of sub-processes etc.
# Only use with one file at a time, as the multithreading will spam the console.
# Options: 'true', 'false'
DEBUG = false
# HIDE_CURSOR: Hides the cursor while printing in the console.
# Options: 'true', 'false'
HIDE_CURSOR = false

[video]
# CONVERT_DOLBY_VISION_TO_P8: Checks HEVC files for Dolby Vision metadata. 
# If the Dolby Vision Profile is Profile 7 Full Enhancement Layer (FEL), 
# it will convert to a compatible Reference Processing Unit (RPU) that most players can use.
# The result is a Profile 8.1 file with Base Layer (HDR10) and a compatible 
# RPU (dynamic metadata stream: brightness, contrast etc) stream. Profile 5 will not be converted.
# Options: 'true', 'false'
CONVERT_DOLBY_VISION_TO_P8 = true

[audio]
# PREFERRED_AUDIO_LANG: Removes any audio tracks that does not
# match those languages. Leave empty to keep all tracks.
# Must be in ISO-639-2/B (3-letter) format.
# Example: "eng, nor"
PREFERRED_AUDIO_LANG =
# ONLY_KEEP_ONE_MATCHING_AUDIO_TRACK: Only keep one audio track
# of each language match, skipping multiple versions. If set
# to 'false', all language matched subtitle tracks will be kept.
# Options: 'true', 'false'
ONLY_KEEP_ONE_MATCHING_AUDIO_TRACK = false
# PREFERRED_AUDIO_FORMATS:
#
# ORIG            - Original Audio
# AAC             - Up to 8 channels, 7.1 Surround
# Even-Out-Sound  - Up to 8 channels, 7.1 Surround
# Even-Out-Sound+ - Up to 8 channels, 7.1 Surround
# FLAC            - Up to 8 channels, 7.1 Surround
# OPUS            - Up to 8 channels, 7.1 Surround
# WAV             - Up to 8 channels, 7.1 Surround
# AC3             - Up to 6 channels, 5.1 Surround
# DTS             - Up to 6 channels, 5.1 Surround
# EAC3            - Up to 6 channels, 5.1 Surround
# COPY            - Keep ALL audio tracks as-is, no filtering. Ignores PREFERRED_AUDIO_LANG.
#
# Downmixing is specified with ":", like ":5.1" or ":2.0"
# EOS = Even-Out-Sound, applies dynamic audio leveling and dialogue focused mixing.
# EOS+ = Even-Out-Sound+, applies dynamic audio leveling and even stronger dialogue focused mixing.
# EOS format is specified with "-<FORMAT>". Default format is AC3 (Dolby Digital).
#
# Examples:
# "ORIG, EOS-DTS:5.1"
# "EOS:2.0, AAC:2.0"
# "ORIG, EOS+-DTS"
PREFERRED_AUDIO_FORMATS = ORIG, EOS-AC3
# REMOVE_COMMENTARY_TRACK: 'true', 'false'
REMOVE_COMMENTARY_TRACK = true

[subtitles]
# PREFERRED_SUBS_LANG: Removes any subtitle tracks that does not
# match those languages. Leave empty to keep all tracks.
# Must be in ISO-639-2/B (3-letter) format.
# Example: "eng, nor"
PREFERRED_SUBS_LANG =
# ONLY_KEEP_ONE_MATCHING_SUBTITLE: Only keep one subtitle
# of each language match, skipping multiple versions. If set
# to 'false', all language matched subtitle tracks will be kept.
# Options: 'true', 'false'
ONLY_KEEP_ONE_MATCHING_SUBTITLE = false
# OCR_LANGUAGES: Select the languages that will
# be converted to SRT. Must be in ISO-639-2/B (3-letter) format.
# Example: "eng, nor"
# "all" = OCR all subtitles
# "none" = do not OCR any subtitles
OCR_LANGUAGES = all
# MAIN_AUDIO_LANGUAGE_SUBS_ONLY: Only keep/download
# subtitles that matches the main audio language.
# If main audio language subtitles are not found,
# and DOWNLOAD_MISSING_SUBS is set to false, it will
# keep the original subtitles.
# Options: 'true', 'false'
MAIN_AUDIO_LANGUAGE_SUBS_ONLY = false
# DOWNLOAD_MISSING_SUBS: Attempt to download
# any missing subtitles from PREFERRED_SUBS_LANG using Subliminal.
# If set to 'override', all included or
# external subtitles will be ignored.
# Options: 'true', 'false', 'override'
DOWNLOAD_MISSING_SUBS = true
# PREFERRED_SUBS_EXT: The preferred subtitle types ordering.
# Note: ALL four subtitle filetypes MUST be assigned.
PREFERRED_SUBS_EXT = ass, srt, sup, sub
# PRIORITIZE_SUBTITLES: If both internal and external subtitles
# of matching languages are found, prioritize based on pref.
# Options: 'internal', 'external'
PRIORITIZE_SUBTITLES = internal
# REMOVE_SDH: 'true', 'false'
REMOVE_SDH = true
# REMOVE_MUSIC: Removes any lines containing 1
# or more "♪" symbols if set to 'true'
REMOVE_MUSIC = true
# ALWAYS_ENABLE_SUBS: Sets the first subtitle to default enabled
# in the output MKV file. Options: 'true', 'false'
ALWAYS_ENABLE_SUBS = false
# REMOVE_ALL_SUBTITLES: Removes all subtitles from MKV file,
# regardless of preferences. Useful for batch-removing bad subtitles.
# Note: Overrides DOWNLOAD_MISSING_SUBS, no subtitles will be kept.
# Options: 'false', 'true'
REMOVE_ALL_SUBTITLES = false
# RESYNC_SUBTITLES: Resyncs downloaded or external subtitles using FFsubsync.
# Internal subtitles will not be resynced, as these are assumed to be correct.
# Options: 'true', 'false'
RESYNC_SUBTITLES = true
# FORCED_SUBTITLES_PRIORITY
# If set to 'first', any identified forced subtitles will be
# placed first in the subtitle ordering and have the forced flag enabled.
# If set to 'last', the forced subtitle track will be placed last and not
# have the forced flag set in the resulting MKV file, ensuring that the
# regular subtitle track is selected first.
# If set to 'skip', no forced subtitles will be kept.
# Options: 'first', 'last', 'skip'
FORCED_SUBTITLES_PRIORITY = first
# KEEP_ORIGINAL_SUBTITLES: 'true', 'false'
KEEP_ORIGINAL_SUBTITLES = true
# REDO_CASING: Fixes any subtitles that are all-uppercase to sentence-case.
# Works well for fixing English subtitles that are all-uppercase,
# but may break with other languages. Requires REMOVE_SDH to be enabled.
# Options: 'true', 'false'
REDO_CASING = false
# NORMALIZE_POSITION: Remove/strip subtitle positioning tags in SRT such
# as {\an8}, which puts subtitles at the top of the screen. Often used 
# for making space for credits but can be distracting. Requires REMOVE_SDH to be enabled.
NORMALIZE_POSITION = false

[integrations]
RADARR_URL = http://127.0.0.1:7878
# Add your Radarr API key to update the file/folder path of processed media files
RADARR_API_KEY =
SONARR_URL = http://127.0.0.1:8989
# Add your Sonarr API key to update the file/folder path of processed media files
SONARR_API_KEY =

[media-encoder]
# ENABLE_MEDIA_ENCODER
# Options: true, false
ENABLE_MEDIA_ENCODER = false
# OUTPUT_CODEC: The output codec used for video encoding.
# Options:
# 'h264' - H.264/AVC (x264)
# 'h265' - H.265/HEVC (x265)
# 'av1'  - AOMedia Video 1 (libsvtav1)
# 'vp9'  - VP9 (libvpx-vp9)
OUTPUT_CODEC = h265
# QUALITY_CRF: The quality setting (Constant Rate Factor) used for
# calculating the minimum required video bitrate given a quality number.
# CRF 19 ~= 2160p (Speed: Slow) - Effectively transparent from source in most cases (perfect for REMUX)
# CRF 21 <= 1080p (Speed: Slow) - Effectively transparent from source in most cases (perfect for REMUX)
# CRF 20 <= 1080p (Speed: Medium) - More space saving, with minimal loss to some high-level details
# Options:
# 0 (lossless) -> 51 (highest compression)
# Resolution specific overrides can be defined with ":<horizontal_res>-<crf>".
# Example: 
# "21:3840-23" - Use CRF-21 for all resolutions, unless file is 4K (3840 horizontal res) then use CRF-23
QUALITY_CRF = 21:3840-19
# CROP_VALUES: Crop values defined in pixels: (left,right,top,bottom).
# Useful for cropping black bars in the video.
# Options: <blank>, 'auto', <left>,<right>,<top>,<bottom>
# Example: '0,0,104,104'
CROP_VALUES = auto
# ENCODING_SPEED: The speed to be used for encoding. For lower CRF values (<20)
# Using 'medium' is sufficient in most cases (even with grainy video),
# but for higher compression ratios (>20), using speed 'slow' is recommended.
# If the source video is grainy you should also apply tune 'grain' to preserve details.
# Options:
# H.264/H.265 - 'medium', 'slow', 'slower'
# AV1         - '0-13' (slow -> fastest), 'medium' maps to '6', 'slow' = '4', 'slower' = '2'
# VP9         - '0-8' (slow -> fastest), 'medium' maps to '4', 'slow' = '0', 'slower' = '0'
ENCODING_SPEED = slow
# LIMIT_RESOLUTION: Limit the horizontal resolution of the video.
# Useful for downscaling 4K video to 1080p or 720p.
# Examples:
# '1920' -> downscale to 1080p (resolution may be 1920x802 if black bars are removed)
# '1280' -> downscale to 720p
LIMIT_RESOLUTION =
# TUNE: The tuning preset to be used by the encoder, useful when using higher compression values.
# h264 - 'film', 'animation', 'grain', 'stillimage', 'fastdecode', 'zerolatency', 'psnr', 'ssim'
# h265 - 'grain', 'fastdecode', 'zerolatency', 'psnr', 'ssim', 'animation'
# av1  - 'ssim', 'psnr'
# vp9  - (none)
TUNE = grain
# CUSTOM_PARAMS: Custom FFmpeg parameters, do not use any single
# or double quotes. If still needed, make sure to use "double" to prevent escaping.
# Example: CUSTOM_PARAMS = -vf ''bwdif=mode=0:parity=tff:deint=all''
CUSTOM_PARAMS =