services:
  mkv-auto-service:
    image: ${IMAGE_NAME}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    tty: true
    volumes:
      - ${INPUT_FOLDER}:/mkv-auto/files/input
      - ${OUTPUT_FOLDER}:/mkv-auto/files/output
      - ${TEMP_FOLDER}:/mkv-auto/files/tmp
      - ${CONFIG_FOLDER}:/mkv-auto/config
      - ${HOST_FOLDER}/logs:/mkv-auto/logs
    entrypoint: ["/bin/bash", "/mkv-auto/service-entrypoint.sh"]
    environment:
      - DEBUG_MODE=${DEBUG_MODE}