services:
  qbittorrent-service:
    build: .
    container_name: qbittorrent-automation
    restart: unless-stopped
    user: "1000:1000"
    tty: true
    environment:
      - QBITTORRENT_URL=${QBITTORRENT_URL}
      - QBITTORRENT_USERNAME=${QBITTORRENT_USERNAME}
      - QBITTORRENT_PASSWORD=${QBITTORRENT_PASSWORD}
      - TARGET_TAG=${TARGET_TAG}
      - TRANSLATE_WINDOWS_PATHS=${TRANSLATE_WINDOWS_PATHS}
      - INPUT_FOLDER=/app/input
      - MAPPINGS_FILE=/app/configs/drive-mappings.txt
    volumes:
      - ${MKV_AUTO_INPUT_FOLDER}:/app/input
      - ./configs:/app/configs
